# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1my68TKBr0-g7nNCT7dUW51Ex06e2boIm
"""

a = int(input())
b = int(input())
if (a > b):
  print(a)
elif (a == b):
  print('числа равны')
else:
  print(b)